name: tests c++20

on:
  push:
  pull_request:

jobs:
  test-gcc-cpp20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
           sudo apt install gcc-10 g++-10
    - name: build library
      run: make COMPILER=g++-10 STD=c++20
    - name: build tests
      working-directory: tests
      run: make tests COMPILER=g++-10 STD=c++20
    - name: dos2unix
      working-directory: tests/integration/expected
      run: |
           sudo apt install dos2unix
           dos2unix *.txt
    - name: run tests
      working-directory: tests
      run: python3 run-tests.py gcc
  test-clang-cpp20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
    - name: build library
      run: make COMPILER=clang++ STD=c++20
    - name: build tests
      working-directory: tests
      run: make tests COMPILER=clang++ STD=c++20
    - name: dos2unix
      working-directory: tests/integration/expected
      run: |
           sudo apt install dos2unix
           dos2unix *.txt
    - name: run tests
      working-directory: tests
      run: python3 run-tests.py clang
  test-msvc-cpp20:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: dependencies
      run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
    - name: build library
      run: make COMPILER=msvc STD=c++20
    - name: build tests
      working-directory: tests
      run: make tests COMPILER=msvc STD=c++20
    - name: dos2unix
      working-directory: tests/integration/expected
      run: dos2unix *.txt
    - name: run tests
      working-directory: tests
      run: python3 run-tests.py msvc
  # TODO: Get this working
  #test-gcc-windows-cpp20:
  #  runs-on: windows-2019
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: dependencies
  #    run: |
  #         python3 -m pip install --upgrade pip
  #         python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
  #         which g++
  #         choco upgrade mingw
  #         refreshenv
  #         which g++
  #  - name: build library
  #    run: make COMPILER=g++ STD=c++20
  #  - name: build tests
  #    working-directory: tests
  #    run: |
  #         make tests COMPILER=g++ STD=c++20
  #         ldd bin/integration.exe
  #         echo $Env:PATH
  #         ls C:/Strawberry/c/bin/
  #         cp C:/Strawberry/c/bin/libstdc++-6.dll bin # attempt to fix dll conflict leading to 0xC0000135
  #  - name: dos2unix
  #    working-directory: tests/integration/expected
  #    run: dos2unix *.txt
  #  - name: run tests
  #    working-directory: tests
  #    run: python3 run-tests.py gcc_windows
  test-clang-windows-cpp20:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install git+https://github.com/jeffkaufman/icdiff.git
    - name: build library
      run: make COMPILER=clang++ STD=c++20
    - name: build tests
      working-directory: tests
      run: make tests COMPILER=clang++ STD=c++20
    - name: dos2unix
      working-directory: tests/integration/expected
      run: dos2unix *.txt
    - name: run tests
      working-directory: tests
      run: python3 run-tests.py clang_windows
